### ISSUE TITLE
Error 1064 when no articles selected for Highlighter to display

### ISSUE THREAD

**Issue by EHCong** [GavickPro/Highlighter-GK5#10]
I am in process of upgrading from Joomla 2.5 to 3.4.1, so did a test upgrade, and then upgraded Highlighter to the J3 version. The site crashed, with a 1064 error. After some debugging, I realised that no articles met the selection criteria, and this generated the invalid SQL call. It was OK with the J2.5 version, but when I turned on debug to see the calls, it also crashed with the same error at the same place. Not surprising, as the code is the same at this point. The debug message is as below.

SELECT
            content.id AS iid,
            content.access AS access,
            categories.title AS catname, 
            users.email AS author_email,
            content.created_by_alias AS author_alias,
            content_rating.rating_sum AS rating_sum,
            content_rating.rating_count AS rating_count,

  CASE WHEN CHAR_LENGTH(content.alias) 
                THEN CONCAT_WS(":", content.id, content.alias) 
                    ELSE content.id END as id, 

  CASE WHEN CHAR_LENGTH(categories.alias) 
                THEN CONCAT_WS(":", categories.id, categories.alias) 
                    ELSE categories.id END as cid           

  FROM 
            jos_content AS content 

  LEFT JOIN 
                jos_categories AS categories 

  ON categories.id = content.catid 

  LEFT JOIN 
                jos_users AS users 

  ON users.id = content.created_by          

  LEFT JOIN 
                jos_content_rating AS content_rating 

  ON content_rating.content_id = content.id

  WHERE 

  ORDER BY 
             content.ordering DESC
Explain
Error
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY content.ordering DESC' at line 28 SQL=EXPLAIN SELECT content.id AS iid, content.access AS access, categories.title AS catname, users.email AS author_email, content.created_by_alias AS author_alias, content_rating.rating_sum AS rating_sum, content_rating.rating_count AS rating_count, CASE WHEN CHAR_LENGTH(content.alias) THEN CONCAT_WS(":", content.id, content.alias) ELSE content.id END as id, CASE WHEN CHAR_LENGTH(categories.alias) THEN CONCAT_WS(":", categories.id, categories.alias) ELSE categories.id END as cid   FROM jos_content AS content LEFT JOIN jos_categories AS categories ON categories.id = content.catid LEFT JOIN jos_users AS users ON users.id = content.created_by LEFT JOIN jos_content_rating AS content_rating ON content_rating.content_id = content.id WHERE ORDER BY content.ordering DESC
Profile
Call Stack
JROOT/modules/mod_highlighter_gk5/gk_classes/gk.source.joomla.php:238
JROOT/modules/mod_highlighter_gk5/helper.php:93
JROOT/modules/mod_highlighter_gk5/mod_highlighter_gk5.php:21
JROOT/libraries/cms/module/helper.php:190
JROOT/libraries/joomla/document/html/renderer/module.php:103
JROOT/libraries/joomla/document/html/renderer/modules.php:43
JROOT/libraries/joomla/document/html/html.php:411
JROOT/libraries/joomla/document/html/html.php:697
JROOT/libraries/joomla/document/html/html.php:477
JROOT/libraries/cms/application/cms.php:1059
JROOT/libraries/cms/application/site.php:729
JROOT/libraries/cms/application/cms.php:258
JROOT/index.php:40
[Add xdebug.file_link_format directive to your php.ini file to have links for files.]

It seems as though if no articles are available to display, an incorrect line of SQL is generated and executed, where all that is really needed is to just display a blank line, which is what happens in J2.5

**Comment by dziudek** [comment]
Hello,

I will fix this issue in the next module release.

**Comment by effidoc** [comment]
hi, I had the same problem in joomla 3-4-1 !
![gk5-with-no-nrws](https://cloud.githubusercontent.com/assets/5610183/7722570/cfcfc790-fee1-11e4-9c48-761d304c9298.png)

**Comment by peterpeter** [comment]
Knock knock. Nearly one year later, it seems the same problem still exists. It crashed a client site yesterday. 

The second query (executed wether there are articles or not) in ../modules/mod_highlighter_gk5/gk_classes/gk.source.joomla.php in function getArticles() throws a catchable (DB-)RuntimeError. 

I wraped that second query in a if block: 
if($second_sql_where)

Or other solution of course is to catch that error in a try/catch block.

Would be cool if you can add a fix for that, as my fix is not getting overwritten by the next update. 
Thank you.

**Comment by EHCong** [comment]
Hi,
Just installed the latest update, and this issue still exists!

**Comment by EHCong** [comment]
Hi, just installed the latest update, and issue has not been addressed. lease fix.

**Comment by EHCong** [comment]
Hi,
Just installed the latest update, and this issue has not been fixed. Please look at it.

**Comment by dziudek** [comment]
@EHCong - please try to use these patches:

https://github.com/GavickPro/Highlighter-GK5/commit/9accdf98661ed8d9818a54795210b3d42f9405c6
https://github.com/GavickPro/Highlighter-GK5/commit/0c6a346a7ff38231346e7091a29e2e2daa9b30ef

**Comment by EHCong** [comment]
Thanks. That's fixed the problem, and much more elegantly than the hack I used.

**Comment by Nail-84** [comment]
Hello! Mr. dziudek  please, help me. I have the same problem. It appears when the publication period of the selected news ends. 

1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY content.ordering ASC' at line 28 SQL=SELECT content.id AS iid, content.access AS access, categories.title AS catname, users.email AS author_email, content.created_by_alias AS author_alias, content_rating.rating_sum AS rating_sum, content_rating.rating_count AS rating_count, CASE WHEN CHAR_LENGTH(content.alias) THEN CONCAT_WS(":", content.id, content.alias) ELSE content.id END as id, CASE WHEN CHAR_LENGTH(categories.alias) THEN CONCAT_WS(":", categories.id, categories.alias) ELSE categories.id END as cid FROM #__content AS content LEFT JOIN #__categories AS categories ON categories.id = content.catid LEFT JOIN #__users AS users ON users.id = content.created_by LEFT JOIN #__content_rating AS content_rating ON content_rating.content_id = content.id WHERE ORDER BY content.ordering ASC

Can this be fixed?
Thanks!

**Comment by dziudek** [comment]
@Nail-84 as I wrote earlier - please try to use these patches:

https://github.com/GavickPro/Highlighter-GK5/commit/9accdf98661ed8d9818a54795210b3d42f9405c6
https://github.com/GavickPro/Highlighter-GK5/commit/0c6a346a7ff38231346e7091a29e2e2daa9b30ef

**Comment by Nail-84** [comment]
Good Day!  Thanks for help! Now in 1064 there is no error. But the shows: 

Parse error: syntax error, unexpected end of file in... \modules\mod_highlighter_gk5\gk_classes\gk.source.joomla.php on line 267

**Comment by dziudek** [comment]
Did you tried to directly copy this file content: https://github.com/GavickPro/Highlighter-GK5/blob/9accdf98661ed8d9818a54795210b3d42f9405c6/mod_highlighter_gk5/gk_classes/gk.source.joomla.php ?

**Comment by Nail-84** [comment]
No. I only add 3 and remove 2 the rows that are specified in the first patch.

That's how I got:

[gk.source.joomla.txt](https://github.com/GavickPro/Highlighter-GK5/files/401057/gk.source.joomla.txt)

**Comment by dziudek** [comment]
That's why the better solution is copying the whole file ;)

Please remove `+// EOF` from the end of your file - it causes a syntax error (the `+` sign comes from Github diff, not from my code ;))

**Comment by Nail-84** [comment]
I tried to copy the entire code here

https://github.com/GavickPro/Highlighter-GK5/blob/9accdf98661ed8d9818a54795210b3d42f9405c6/mod_highlighter_gk5/gk_classes/gk.source.joomla.php ?

Delete, and +.  Now, once again it shows an error 1064  :)

1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY content.ordering ASC' at line 29 SQL=SELECT content.id AS iid, content.access AS access, categories.title AS catname, users.email AS author_email, content.created_by_alias AS author_alias, content_rating.rating_sum AS rating_sum, content_rating.rating_count AS rating_count, CASE WHEN CHAR_LENGTH(content.alias) THEN CONCAT_WS(":", content.id, content.alias) ELSE content.id END as id, CASE WHEN CHAR_LENGTH(categories.alias) THEN CONCAT_WS(":", categories.id, categories.alias) ELSE categories.id END as cid FROM #__content AS content LEFT JOIN #__categories AS categories ON categories.id = content.catid LEFT JOIN #__users AS users ON users.id = content.created_by LEFT JOIN #__content_rating AS content_rating ON content_rating.content_id = content.id WHERE + 1=1 AND ORDER BY content.ordering ASC

This may be due, I'm working right now on a local server?

**Comment by dziudek** [comment]
Are you sure that you have copied the file? Because in your error I see `+ 1=1` what suggest that it is the same issue as with the `+// EOF`

**Comment by Nail-84** [comment]
Yes, I totally copied this code. 

That's how I got:

[gk.source.joomla.zip](https://github.com/GavickPro/Highlighter-GK5/files/401366/gk.source.joomla.zip)

**Comment by dziudek** [comment]
@Nail-84 - please try to use the following one: https://github.com/GavickPro/Highlighter-GK5/blob/de6999fd933b4c058ed7c362de93b52392b090be/mod_highlighter_gk5/gk_classes/gk.source.joomla.php

**Comment by Nail-84** [comment]
Thank You Very Much!  Thanks!

 Front opened, only shows:

Warning: array_merge(): Argument #1 is not an array in... \mod_highlighter_gk5\gk_classes\gk.source.joomla.php on line 260 

Is it possible to fix this?

**Comment by dziudek** [comment]
This one should solve your issue with Warning: https://github.com/GavickPro/Highlighter-GK5/blob/J!3-compatible/mod_highlighter_gk5/gk_classes/gk.source.joomla.php

**Comment by Nail-84** [comment]
Thank You!!! Everything works perfectly and error is gone!
Now I will try to the web server. 

Best wishes! And thanks again for your help!

**Comment by Nail-84** [comment]
I have tortured  :)

On the Web server shows errors

Notice: Undefined offset: 0 in /modules/mod_highlighter_gk5/gk_classes/gk.source.joomla.php on line 260

Notice: Undefined index: text in /modules/mod_highlighter_gk5/helper.php on line 134

Notice: Undefined index: title in /modules/mod_highlighter_gk5/helper.php on line 135

**Comment by dziudek** [comment]
Please just disable the notices - I will look at these notices in my free time as it doesn't look critical.

**Comment by Nail-84** [comment]
Thank you! So I did and turned off the error messages in Joomla.

Best Regards!
