### ISSUE TITLE
Backend problem

### ISSUE THREAD

**Issue by fleurdelysee** [GavickPro/Highlighter-GK5#12]
Hi,
There is many missing options on the Highlighter-GK5 backend panel. 
How to fix it?
Thanks for your help!
![backend problem](https://cloud.githubusercontent.com/assets/20068029/16465979/5c382624-3e0f-11e6-9cdc-314c2257af20.png)

**Comment by dziudek** [comment]
Hi,

First of all please reinstall the module and please also refresh your browser cache after the reinstall.

**Comment by fleurdelysee** [comment]
Hi Tomasz,
It's ok now. 
Thank you!
